name: Publish to conda-forge

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Install dependencies
        run: |
          CONDA_NO_PLUGINS=true conda env create -f environment.yml
          conda init bash
          source ~/.bashrc
          conda activate blockrand_q_designer

      - name: Build the package
        run: |
          conda install conda-build
          conda build .

      - name: Find built package path
        id: find-package
        run: echo "::set-output name=package-path::$(find /home/runner/miniconda3/conda-bld/ -name '*.tar.bz2')"

      - name: Upload to conda-forge
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda install anaconda-client
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          anaconda upload --user conda-forge ${{ steps.find-package.outputs.package-path }}